### ISSUE TITLE
Error in object name

### ISSUE THREAD

**Issue by B1ON1C** [IdentityModel/IdentityModel#588]
As you can see in the references, in most cases it's written "Backchannel":

https://github.com/IdentityModel/IdentityModel/blob/7f8abed00c7d3c82bbc7c64e60688889f2dcb18b/src/OidcConstants.cs#L130
https://github.com/IdentityModel/IdentityModel/blob/7f8abed00c7d3c82bbc7c64e60688889f2dcb18b/src/OidcConstants.cs#L146
https://github.com/IdentityModel/IdentityModel/blob/7f8abed00c7d3c82bbc7c64e60688889f2dcb18b/src/OidcConstants.cs#L201

However, on the next line, it writes "Back**C**hannel"
https://github.com/IdentityModel/IdentityModel/blob/7f8abed00c7d3c82bbc7c64e60688889f2dcb18b/src/OidcConstants.cs#L524

Could it be a mistake or was it designed that way for some reason?
Thanks!

**Comment by josephdecock** [comment]
It would be good to standardize on a consistent casing of front- and back-channel but it is hard to do that now because the most straightforward refactor is a breaking change. If you search for both frontchannel and backchannel, we do have a mixture of casings for both. Ultimately the "correct" thing is somewhat ambiguous: protocol parameters always treat frontchannel and backchannel as one word, but the specification names are themselves inconsistent:
we have "OpenID Connect **Back-Channel** Logout 1.0" but "OpenID Connect Client-Initiated **Backchannel** Authentication Flow"

We could consider picking a naming style and then adding corrected constants and classes that aliased the existing names while deprecating the old ones in the next major release. Then in a subsequent major release we could ultimately remove them. But, downsides to this approach:
- When we do ultimately remove the deprecated constants etc, we will break users (even if we deprecate it first, people skip major versions all the time)
- In between, we would have duplicate constants which make the developer experience worse (the user's tooling might suggest multiple code completions that look very similar and now you have to look closely at which one you want and make sure you don't accidentally get the deprecated one. No one is going to remember which way the capitalization is "supposed" to be.)

So, my judgement right now is that the benefit doesn't outweigh the breaking changes needed.

**Comment by B1ON1C** [comment]
Thank you very much for the response!
